# Cleaning and summarizing the data



calculating daily returns for NYSE and merging sectors and industry data. 
```{r}

load("Data/NYSE_Stock_Data.Rda")
Yearly_returns <- 
  NYSE %>% 
  arrange(company, date) %>%
  group_by(company) %>%
  mutate(daily_return = percentage_change(adj_close, lag = 1)) %>%
  mutate(year = lubridate::year(date)) %>%
  group_by(company, year) %>%
  summarise(yearly_return = prod(1 + daily_return) - 1, ndays = n()) 
  

NYSE_companies <- read.csv("Data/NYSE_companylist.csv", stringsAsFactors = FALSE, na.strings = "n/a")

Yearly_returns <-  
  Yearly_returns %>%
  left_join(NYSE_companies %>% select(company = Symbol, market_cap_2015 = MarketCap, Sector, Industry,IPOyear,Name)) 

  Yearly_returns=Yearly_returns[order(Yearly_returns$yearly_return,decreasing=TRUE),]
  Yearly_returns=Yearly_returns[order(Yearly_returns$year,decreasing=TRUE),]
  NYSE_Y_Returns=subset(Yearly_returns,! is.na(Yearly_returns$yearly_return))
  write.csv(NYSE_Y_Returns,file="NYSE_Y_returns.csv")

Yearly_returns1 <- 
  Yearly_returns %>%
  group_by(year) %>%
  mutate(top_10 = percent_rank(yearly_return) >= .90)  

Table_1 <- 
  Yearly_returns1 %>%
  group_by(Industry, year, top_10) %>%
  summarize(count = n()) %>%
  spread(value = count, key = top_10, fill = 0) %>%
  rename(bottom_90 = `FALSE`, top_10 = `TRUE`) %>% .[,-5] %>%
  mutate(proportion = top_10 / (bottom_90 + top_10)) %>%
  arrange(year, proportion)


#NYSE_sectors=merge(NYSE,companies,by.x=7,by.y=1)
#NYSE_sectors=NYSE_sectors[order(NYSE_sectors$company,decreasing = FALSE),]
#NYSE_sectors$daily_return=percentage_change(NYSE_sectors$adj_close,lag=1)
#NYSE_daily_returns=NYSE_daily_returns[is.finite(NYSE_daily_returns)]
#NYSE_sectors=NYSE_sectors[-c(nrow(NYSE_sectors))]
#NYSE_sectors$daily_returns=NYSE_daily_returns
#save(NYSE_sectors, file = "NYSE_Returns_Data.Rda")
```

# calculating daily returns for NASDAQ and merging sectors and industry data. 
```{r}
load("Data/NASDAQ_Stock_Data.Rda")
Yearly_returns <- 
  NASDAQ %>% 
  arrange(company, date) %>%
  group_by(company) %>%
  mutate(daily_return = percentage_change(adj_close, lag = 1)) %>%
  mutate(year = lubridate::year(date)) %>%
  group_by(company, year) %>%
  summarise(yearly_return = prod(1 + daily_return) - 1, ndays = n()) 
  

NASDAQ_companies <- read.csv("Data/NASDAQ_companylist.csv", stringsAsFactors = FALSE, na.strings = "n/a")

Yearly_returns <- 
  Yearly_returns %>%
  left_join(NASDAQ_companies %>% select(company = Symbol, market_cap_2015 = MarketCap, Sector, industry,IPOyear,Name)) 

  Yearly_returns=Yearly_returns[order(Yearly_returns$yearly_return,decreasing=TRUE),]
  Yearly_returns=Yearly_returns[order(Yearly_returns$year,decreasing=TRUE),]
  NASDAQ_Y_Returns=subset(Yearly_returns,! is.na(Yearly_returns$yearly_return))
  NASDAQ_Y_Returns=merge(NASDAQ_Y_Returns,Market_Return,by.x=2,by.y=1)
 # write.csv(NASDAQ_Y_Returns,file="NASDAQ_Y_returns.csv")
  
#load("~/Desktop/Honors-/NASDAQ_Stock_Data.Rda")
#NASDAQ_companies <- read.csv("NASDAQ_companylist.csv", stringsAsFactors = FALSE, na.strings = "n/a")
#NASDAQ_sectors=merge(NASDAQ,NASDAQ_companies,by.x=7,by.y=1)

#NASDAQ_sectors=NASDAQ_sectors[order(NASDAQ_sectors$date,decreasing = FALSE),]

#NASDAQ_daily_returns=percentage_change(NASDAQ_sectors$adj_close,lag=1)
#NASDAQ_daily_returns=NASDAQ_daily_returns[is.finite(NASDAQ_daily_returns)]
#NASDAQ_sectors$daily_returns=NASDAQ_daily_returns
#save(NASDAQ_sectors, file = "NASDAQ_Returns_Data.Rda")
```



```{r}

#"Advance_decline Line calculation " " AD= (#winning companies-#of losing companies) +AD(t-1)"

# Total number of companies per year 
NYSE_Companies_per_year=as.data.frame(table(NYSE_Y_Returns$year))
NYSE_Companies_per_year=rename(NYSE_Companies_per_year,year = `Var1`, total_comps = `Freq`)

# Number of companies with yearly return>0 per year
NYSE_Winning_comps=as.data.frame(table(subset(NYSE_Y_Returns,yearly_return>0)$year))
NYSE_Winning_comps=rename(NYSE_Winning_comps,year = `Var1`, winning = `Freq`)

# Number of companies with yearly return>0 per year
NYSE_Losing_comps=as.data.frame(table(subset(NYSE_Y_Returns,yearly_return<0)$year))
NYSE_Losing_comps=rename(NYSE_Losing_comps,year = `Var1`, losing = `Freq`)

# Merging above tables and summarizing it to create data for AD calculations 
AD_line_data=merge(NYSE_Winning_comps,NYSE_Losing_comps,by.x=1, by.y =1)
AD_line_data$total=NYSE_Companies_per_year$total_comps
AD_line_data$percWin=AD_line_data$winning/AD_line_data$total
AD_line_data$percLose=AD_line_data$losing/AD_line_data$total
AD_line_data$WinLoseDiff=AD_line_data$winning-AD_line_data$losing

# Calculating AD_line 
AD_line_data$AD_line[1]=AD_line_data$WinLoseDiff[1]
for(i in 2:nrow(AD_line_data)){
  AD_line_data$AD_line[i]=AD_line_data$WinLoseDiff[i]+AD_line_data$AD_line[i-1]
}
plot(AD_line_data$year,AD_line_data$AD_line,main="Advance/Decline Line",xlab="Years",Ylab="AD_line(#win-#lost+AD(t-1) *t=Time",type="l",col="red")
lines(AD_line_data$year,AD_line_data$AD_line,type="l",col="red")

plot(AD_line_data$year,AD_line_data$WinLoseDiff,main="difference between the number of winning and losing companies",xlab="Years",Ylab="win-lose")
lines(AD_line_data$year,AD_line_data$WinLoseDiff,type="l",col="red")

write.csv(AD_line_data,file="NYSE_AD_Line_data.csv")
```


 




```{r}
#"Number of companies with annual returns adding up to 10% of Market Returns"
companies=c()
year=c()
percent=0.1
for(i in c(1987:2015)){
  n=0
  number_of_companies=0
  year=c(year,i)
  term=which(SP_Y_Returns$year==i) # Returns the list of indexs of the year i
  term=term[1]
  while(n<percent){
    n=n+SP_Y_Returns$Market_Weight[term]
    print(n)
    number_of_companies=number_of_companies+1
    print(number_of_companies)
    term=term+1
  }
  companies=c(companies,number_of_companies)
}
comp10=data.frame(companies,year)
comp10=rename(comp10,top10=`companies`)


comp20=data.frame(companies,year)
comp20=rename(comp20,top20=`companies`)

total_companies=as.data.frame(table(SP_Y_Returns$year))
total_companies=rename(total_companies,year=`Var1`,companies=`Freq`)

compNum=merge(comp10,comp20)

marketShare=merge(compNum,total_companies)
marketShare$top10_ratio=marketShare$top10/marketShare$companies
marketShare$top20_ratio=marketShare$top20/marketShare$companies

# get company info using the indexes in comp
topComps=c()
companies=c()
for(i in 1:length(comp10$year)){
    print(i)
    print(comp10$year[i])
    term=which(SP_Y_Returns$year==comp10$year[i])
    print(comp10$top10[i])
    topComps=SP_Y_Returns[term[1:comp10$top10[i]],]
    companies=rbind(companies,topComps)
    }
  
View(table(companies$year,companies$Sector))
  

```

#Junk code
```{r}
 # calculating 5-year return
number_of_years=5
counter=0
for(i in (1986:2015)){
  data=Returns[order(Returns$company),]
  group_by(data,company)
  compTable=as.data.frame(table(data$company))
  compTable=rename(compTable,company= `Var1`, company_years = `Freq`)
  data=merge(data,compTable,by.x=1,by.y=1)
  
  first5=subset(Returns,Returns$year<1991)
  fiveYear_Return <-
    first5=first5[order(first5$company),] %>%
    group_by(company,year) %>%
    summarise(fiveYear_Return=sum(yearly_returns))
    
  while(counter<5){
    
  }
}
  


```

